name: Create a release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: pr
        with:
          state: closed
      - name: Find release name and tag name
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ steps.pr.outputs.title }}
          separator: ' - '
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.split.outputs._0 }}
          tag_name: ${{ steps.split.outputs._1 }}
          generate_release_notes: true
