name: Create a release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: pr
        with:
          state: closed
      - run: echo "title - ${RELEASE_TITLE}; tag - ${RELEASE_TAG}"
        if: success() && steps.pr.outputs.title
        env:
          RELEASE_TITLE: ${{ steps.pr.outputs.title.split(' - ')[0] }}
          RELEASE_TAG: ${{ steps.pr.outputs.title.split(' - ')[1] }}
